DEFAULT_ARCH=           i386
EMULATIONS=             &i386elf,
DEFAULT_EMULATION=      i386elf
TARGET_ALIAS=           i386-just-dragonfly
TARGET_CANONICAL=       i386-just-dragonfly
TARGET_CPU=             i386

SRCS+=	obj-elf.c tc-i386.c atof-ieee.c
