load("//sys:build_defs.bzl", "dfly_kernel_lib")

dfly_kernel_lib(
    name = "sha2",
    srcs = ["sha2.c"],
    deps = ["//sys/sys"],
    hdrs = ["sha2.h"],
    include_prefix = "crypto/sha2",
    visibility = ["//visibility:public"],
)
