TARGET_TUPLE?=	i386-just-dragonfly

NATIVE_EMULATION=	elf_i386
HOST=			${TARGET_TUPLE}
FLAGS_GROUPS=		emul
emul_FLAGS=		-DDEFAULT_EMULATION=\"${NATIVE_EMULATION}\" \
			-DTARGET=\"${TARGET_TUPLE}\"
emul_FLAGS_FILES=	ldmain.c

_i386_path=	${USRDATA_PREFIX}/lib:${USRDATA_PREFIX}/usr/lib

.for EMUL in ${NATIVE_EMULATION}
EMS+=			${EMUL}
SRCS+=			e${EMUL}.c
CLEANFILES+=		e${EMUL}.c
. for ext in ${ELF_SCR_EXT}
LDSCRIPTS_${EMUL}+=	${EMUL}.${ext}
. endfor
LDSCRIPTS+=		${LDSCRIPTS_${EMUL}}
.endfor

e${NATIVE_EMULATION}.c ${LDSCRIPTS_${NATIVE_EMULATION}}: \
    emulparams/${NATIVE_EMULATION}.sh emultempl/elf32.em \
    scripttempl/elf.sc genscripts.sh stringify.sed
	sh ${SRCDIR}/ld/genscripts.sh \
		${SRCDIR:Q}/ld \
		${_i386_path:Q} \
		"" \
		"" \
		${HOST} \
		${TARGET_TUPLE:Q} \
		${TARGET_TUPLE:Q} \
		${NATIVE_EMULATION:Q} \
		"" \
		no \
		yes \
		${NATIVE_EMULATION:Q} \
		${TARGET_TUPLE:Q}
