SUBDIR= amdsbwd cmx cpuctl dcons ecc ichwd iichid intelpmic ipmi joy kbdmux \
	lpbb nmdm pcfclock putter snp syscons tbridge coremctl dimm aperf \
	iosf

# Empty for concurrent build
#
SUBDIR_ORDERED=

.include <bsd.subdir.mk>
