SUBDIR=	alpm amdpm aps coretemp
SUBDIR+=intpm kate km lm powernow uguru
SUBDIR+=viapm wbsio perfbias clockmod schsio
SUBDIR+=memtemp corepower amdcstate
#SUBDIR+=amdtdp

# Empty for concurrent build
#
SUBDIR_ORDERED=

.include <bsd.subdir.mk>
