SUBDIR=	alpm amdpm amdsmn amdtemp aps clockmod corecstat corepower coretemp
SUBDIR+=intpm kate km lm memtemp perfbias powernow schsio uguru
SUBDIR+=viapm wbsio

# Empty for concurrent build
#
SUBDIR_ORDERED=

.include <bsd.subdir.mk>
