SUBDIR=	alpm amcstate amdpm amdsmn amdtemp aps clockmod corecstat corepower
SUBDIR+= coretemp intpm kate km lm memtemp perfbias powernow schsio uguru
SUBDIR+=viapm wbsio

# Empty for concurrent build
#
SUBDIR_ORDERED=

.include <bsd.subdir.mk>
