#$FreeBSD: src/sys/modules/i2c/controllers/ichsmb/Makefile,v 1.1 2005/06/05 11:55:29 takawata Exp $

.PATH:		${.CURDIR}/..
KMOD		= vgapci
SRCS		= device_if.h bus_if.h pci_if.h smbus_if.h \
		  vga_pci.c

.include <bsd.kmod.mk>
